trigger:
  tags:
    include:
      - v*
jobs:
- template: bottle.yml
  parameters:
    name: high_sierra
    vmImage: 'macOS-10.13'
    xcode: 9.4.1

- template: bottle.yml
  parameters:
    name: mojave
    vmImage: 'macOS-10.14'
    xcode: 10.2.1
